# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f84349b111fed51b770473faab8ecba965f59dc78f0b5d116cabda47df8de250f5184feac0af9592810a0d8f3cb442717d5c31ebdaddd63585b69d16ebe80bb1

test:
  secret_key_base: c0ccef8fd89ebe435d327392421da81a9ca46befd2e6689e6db22fbb166021d7ce9dedf935138d161f97edd9ffaa50ba411a0ddf986045d5964d204b91cf5d73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
